server:
  port: ${SERVER_PORT:80}

file:
  storage-path: ${FILE_PATH:src/main/resources/files}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:filesaver}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}

    show-sql: false

    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
